spring:
  config:
    name: application
  profiles:
    active: ${config}
    # active: dev

qr-code:
  in: iVBORw0KGgoAAAANSUhEUgAAAxYAAAN7CAYAAADY1AwjAAAAAXNSR0IA
  out: rs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQA
